version: "3.8"

services:
  db:
    image: postgres:alpine
    env_file: .env
    ports:
      - 0.0.0.0:${POSTGRES_EXTERNAL_PORT}:5432
    restart: 'no'
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ImageName}}/{{.ID}}/"